#!/bin/bash -x
NSLOTS=24
#SBATCH -n 24
#SBATCH --time=0:30:00
#SBATCH -J test_csrosetta
### start of jobscript

module load openmpi/gcc

LOGS=logs_`echo $SLURM_JOB_ID | awk -v FS="." '{print $1}'`
mkdir -p $LOGS

## have NSLOTS - 3 worker processes -- determines number of structures per generation...
NSTRUCT=`echo $NSLOTS | awk '{print $1-3}'`


echo "running on $NSLOTS cpus ..."
EXE=$CM_EXECUTEABLE.$CM_EXEC_EXT
CMDLINE="-out:level 300 -mute all_high_mpi_rank_filebuf -out:mpi_tracer_to_file $LOGS/log -database $CM_ROSETTA_DATABASE $CM_COMMANDLINE"
CYCLES=$CM_AUTO_NSTRUCT"-run:test_cycles -jd2::mpi_timeout_factor -1"
$MPI_RUN -n $NSLOTS $EXE $CMDLINE $CYCLES
