#!/bin/bash -x
#MSUB -l nodes=1:ppn=8
#MSUB -l walltime=0:59:00
#MSUB -N test_csrosetta
### start of jobscript
NSLOTS=${NSLOTS:=`cat "$PBS_NODEFILE" | wc -l`}
NSTRUCT=$( echo $NSLOTS | awk '{print $1-3}' )
cd $PBS_O_WORKDIR
echo "workdir: $PBS_O_WORKDIR"
LOGS=logs_`echo $PBS_JOBID | awk -v FS="." '{print $1}'`
mkdir -p $LOGS

echo "running on $NSLOTS cpus ..."
EXE=$CM_EXECUTEABLE.$CM_EXEC_EXT
CMDLINE="-out:level 300 -mute all_high_mpi_rank_filebuf -out:mpi_tracer_to_file $LOGS/log -database $CM_ROSETTA_DATABASE $CM_COMMANDLINE"
CYCLES=$CM_AUTO_NSTRUCT" -run:test_cycles -jd2::mpi_timeout_factor -1"
mpiexec -np $NSLOTS $EXE $CMDLINE $CYCLES
